default: &default
  host: localhost
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci

development:
  <<: *default
  database: birthrightstories_development

test:
  <<: *default
  database: birthrightstories_test

production:
  <<: *default
  database:  birthrightstories_production
  username:  rails
  password:  G9ZEZnCDKO
  reconnect: true